#!/bin/bash
#PBS -A <allocation>
#PBS -l walltime=<walltime>:00:00 # WALLTIME limit
#PBS -l nodes=<nodes>:ppn=<ppn> # Number of nodes, put 16 processes on each
#PBS -l pmem=1500
#PBS -M <e-mail>
#PBS -m e
#PBS -N <tag>
#PBS -q <queue>
#PBS -l feature=<feature>


scratch_dir=<scratch>
cd $scratch_dir

module purge;
module load conda/4.1
module load openmpi-gcc/1.7.3-4.8.2
module load mdanalysis/0.8.1 

<streamm_command>


